// Builds the standalone wasm for browsers (page render + live worklet).
// The binary is embedded as base64 for bundling (stb-vorbis pattern).
// No .wasm fetch is needed, so worklets and file:// work too.
// No Emscripten JS glue, no threads, no filesystem.
// Run from web/:  npx tsx scripts/build-standalone.ts
// Requires emsdk (em++). Override discovery with EMCC or EMSDK.
import child_process from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compileObjects, emxxFor, findEmcc } from "./emu.ts";

const web = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const root = path.resolve(web, "..");
const objectDirectory = path.resolve(web, "out", "obj_sa");
const wasmOutput = path.resolve(web, "out", "smu-standalone.wasm");
const base64Output = path.resolve(web, "out", "smu-standalone.wasm.ts");

const emcc = await findEmcc(root);
const emxx = emxxFor(emcc);
console.info(`EMCC Found: ${emcc}`);

const objects = compileObjects(
    emcc,
    [
        "-std=c++20",
        "-O3",
        "-fno-exceptions",
        "-DSMU_STANDALONE",
        "-Wno-inconsistent-missing-override",
        "-Isrc",
        "-Isrc/compat"
    ],
    objectDirectory,
    root
);

console.info("LINK: out/smu-standalone.wasm");
child_process.execFileSync(
    emxx,
    [
        "-std=c++20",
        "-O3",
        "-fno-exceptions",
        "-DSMU_STANDALONE",
        ...objects,
        "-sSTANDALONE_WASM=1",
        "--no-entry",
        "-sFILESYSTEM=0",
        "-sINITIAL_MEMORY=128MB",
        "-sMAXIMUM_MEMORY=2GB",
        "-sALLOW_MEMORY_GROWTH=1",
        "-sEXPORTED_FUNCTIONS=_smu_init,_smu_shutdown,_smu_set_rom,_smu_reset,_smu_boot,_smu_midi_ready,_smu_run_blank,_smu_load_midi,_smu_song_length,_smu_midi_in,_smu_set_native_engine,_smu_set_native_fx,_smu_native_firmware_share,_smu_render_frames,_smu_song_done,_smu_scheduled_events,_smu_dropped,_smu_error,_smu_error_copy,_smu_sample_rate,_smu_set_usb_host,_malloc,_free",
        "-o",
        wasmOutput
    ],
    { cwd: root, stdio: "inherit" }
);

// Base64 for bundling (the worklet cannot fetch, and file:// has no fetch).
const binary = fs.readFileSync(wasmOutput);
fs.writeFileSync(
    base64Output,
    `// Generated by scripts/build-standalone.ts. Do not edit.\nexport default ${JSON.stringify(binary.toString("base64"))};\n`
);
console.info("OK");
