// Builds out/smu_render.mjs + .wasm (Node offline renderer).
// Run from web/:  npx tsx scripts/build.ts   (or: npm run build:wasm)
// Requires emsdk (emcc/em++). Override discovery with EMCC or EMSDK.
import child_process from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compileObjects, emxxFor, findEmcc } from "./emu.ts";

const web = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const root = path.resolve(web, "..");
const objectDirectory = path.resolve(web, "out", "obj");
const jsOutput = path.resolve(web, "out", "smu_render.mjs");

const emcc = await findEmcc(root);
const emxx = emxxFor(emcc);
console.info(`EMCC Found: ${emcc}`);

const objects = compileObjects(
    emcc,
    [
        "-std=c++20",
        "-O3",
        "-Wno-inconsistent-missing-override",
        "-Isrc",
        "-Isrc/compat"
    ],
    objectDirectory,
    root
);

console.info("LINK: out/smu_render.mjs");
child_process.execFileSync(
    emxx,
    [
        "-O3",
        ...objects,
        "-o",
        jsOutput,
        "-sMODULARIZE=1",
        "-sEXPORT_ES6=1",
        "-sEXPORT_KEEPALIVE=1",
        // One module for the Node renderer and tooling.
        "-sENVIRONMENT=node",
        "-sALLOW_MEMORY_GROWTH=1",
        "-sINITIAL_MEMORY=64MB",
        "-sMAXIMUM_MEMORY=2GB",
        "-sEXPORTED_FUNCTIONS=['_malloc','_free']",
        "-sEXPORTED_RUNTIME_METHODS=['HEAPU8']"
    ],
    { cwd: root, stdio: "inherit" }
);

// Declaration for the generated module, so src/*.ts can import it typed.
fs.writeFileSync(
    path.resolve(web, "out", "smu_render.d.mts"),
    `// Generated by scripts/build.ts. Do not edit.\nimport type { SmuFactory } from "../src/smu-types.ts";\nconst factory: SmuFactory;\nexport default factory;\n`
);
console.info("OK");
