// Loader for the standalone wasm (page render + live worklet).
// The binary is embedded as base64 (generated by build-standalone.ts).
// No fetch is needed: this works in AudioWorklets and from file://.
// Instantiation runs the static constructors (_initialize).
// A few stub imports are provided (clocks are profiling-only).
import wasmData from "../../out/smu-standalone.wasm.ts";
import type { SmuModule } from "../smu-types.ts";

const base64Alphabet =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

// AudioWorklet has no atob.
function atobPolyfill(input: string): string {
    const clean = input.replaceAll(/[\t\n\f\r ]/g, "");
    if (clean.length % 4 === 1) throw new Error("invalid base64 length");
    let output = "";
    let buffer = 0;
    let bits = 0;
    for (const char of clean) {
        if (char === "=") break;
        const value = base64Alphabet.indexOf(char);
        if (value === -1) throw new Error("invalid base64 character");
        buffer = (buffer << 6) | value;
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            output += String.fromCodePoint((buffer >> bits) & 0xff);
        }
    }
    return output;
}

interface StandaloneExports {
    readonly memory: WebAssembly.Memory;
    _initialize(): void;
    readonly malloc: (size: number) => number;
    readonly free: (pointer: number) => void;
    readonly smu_sample_rate: () => number;
    readonly smu_set_usb_host: (on: number) => void;
    readonly smu_init: (usbHost: number) => number;
    readonly smu_shutdown: () => void;
    readonly smu_set_rom: (kind: number, ptr: number, length: number) => number;
    readonly smu_reset: () => number;
    readonly smu_boot: (maxSamples: number) => number;
    readonly smu_midi_ready: () => number;
    readonly smu_run_blank: (nframes: number) => number;
    readonly smu_load_midi: (ptr: number, length: number) => number;
    readonly smu_song_length: () => number;
    readonly smu_midi_in: (port: number, ptr: number, length: number) => number;
    readonly smu_set_native_engine: (mode: number) => void;
    readonly smu_set_native_fx: (mode: number) => void;
    readonly smu_native_firmware_share: () => number;
    readonly smu_render_frames: (outPtr: number, nframes: number) => number;
    readonly smu_song_done: () => number;
    readonly smu_scheduled_events: () => bigint;
    readonly smu_dropped: () => bigint;
    readonly smu_error_copy: (outPtr: number, cap: number) => number;
}

class StandaloneModule implements SmuModule {
    private readonly exports: StandaloneExports;

    public constructor(exports: StandaloneExports) {
        this.exports = exports;
    }

    // Fresh view every time: the buffer is replaced on memory growth.
    public get HEAPU8(): Uint8Array {
        return new Uint8Array(this.exports.memory.buffer);
    }

    public _malloc(size: number): number {
        return this.exports.malloc(size);
    }

    public _smu_sample_rate(): number {
        return this.exports.smu_sample_rate();
    }

    public _free(ptr: number): void {
        this.exports.free(ptr);
    }

    public _smu_init(usbHost: number): number {
        return this.exports.smu_init(usbHost);
    }

    public _smu_set_usb_host(on: number): void {
        this.exports.smu_set_usb_host(on);
    }

    public _smu_set_rom(kind: number, ptr: number, length: number): number {
        return this.exports.smu_set_rom(kind, ptr, length);
    }

    public _smu_reset(): number {
        return this.exports.smu_reset();
    }

    public _smu_boot(maxSamples: number): number {
        return this.exports.smu_boot(maxSamples);
    }

    public _smu_midi_ready(): number {
        return this.exports.smu_midi_ready();
    }

    public _smu_run_blank(nframes: number): number {
        return this.exports.smu_run_blank(nframes);
    }

    public _smu_load_midi(ptr: number, length: number): number {
        return this.exports.smu_load_midi(ptr, length);
    }

    public _smu_song_length(): number {
        return this.exports.smu_song_length();
    }

    public _smu_midi_in(port: number, ptr: number, length: number): number {
        return this.exports.smu_midi_in(port, ptr, length);
    }

    public _smu_set_native_engine(mode: number): void {
        this.exports.smu_set_native_engine(mode);
    }

    public _smu_set_native_fx(mode: number): void {
        this.exports.smu_set_native_fx(mode);
    }

    public _smu_native_firmware_share(): number {
        return this.exports.smu_native_firmware_share();
    }

    public _smu_render_frames(outPtr: number, nframes: number): number {
        return this.exports.smu_render_frames(outPtr, nframes);
    }

    public _smu_song_done(): number {
        return this.exports.smu_song_done();
    }

    public _smu_scheduled_events(): bigint {
        return this.exports.smu_scheduled_events();
    }

    public _smu_dropped(): bigint {
        return this.exports.smu_dropped();
    }

    public _smu_error_copy(outPtr: number, cap: number): number {
        return this.exports.smu_error_copy(outPtr, cap);
    }
}

// Monotonic stub clock (the core reads it for profiling only).
const stubClock = { ticks: 0n };

export async function loadSmu(): Promise<SmuModule> {
    const binary =
        "atob" in globalThis ? atob(wasmData) : atobPolyfill(wasmData);
    // eslint-disable-next-line unicorn/prefer-code-point
    const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0));
    const imports = {
        env: {
            emscripten_notify_memory_growth: () => {
                // Views are recreated on every access, so growth needs nothing.
            }
        },
        wasi_snapshot_preview1: {
            proc_exit: (code: number): number => {
                throw new Error(`proc_exit(${code})`);
            },
            clock_time_get: (
                _clock: number,
                _precision: bigint,
                ptr: number
            ): number => {
                stubClock.ticks += 1_000_000n;
                const view = new DataView(memory.buffer);
                view.setBigUint64(ptr, stubClock.ticks / 1_000_000_000n, true);
                view.setBigUint64(
                    ptr + 8,
                    stubClock.ticks % 1_000_000_000n,
                    true
                );
                return 0;
            },
            fd_write: () => 0,
            fd_read: () => 0,
            fd_close: () => 0,
            fd_seek: () => 0,
            environ_sizes_get: (argcPtr: number, sizePtr: number): number => {
                const view = new DataView(memory.buffer);
                view.setUint32(argcPtr, 0, true);
                view.setUint32(sizePtr, 0, true);
                return 0;
            },
            environ_get: () => 0
        }
    };
    // The import closures only run after instantiation below.
    // Reactor builds run no startup code at instantiate time.
    // This const is therefore ready by the time anything touches it.
    const { instance } = await WebAssembly.instantiate(bytes, imports);
    const memory = (instance.exports as unknown as StandaloneExports).memory;
    const exports = instance.exports as unknown as StandaloneExports;
    // Static constructors: miss this and timers misbehave.
    // Attotime::never would read as zero, firing never-timers at once.
    exports._initialize();
    return new StandaloneModule(exports);
}
